---
- name: Deploy server
  hosts: deploy
  roles:
    - pre_config
    # - deploy
    # - swarm_init

- name: Manager services
  hosts: managers
  roles:
    - pre_config
    # - swarm_join

- name: Worker services
  hosts: workers
  roles:
    - pre_config
    # - swarm_join
