---
- name: Deploy server
  hosts: deploy
  roles:
    - role: pre_config
      tags: preconfig

    - role: deploy
      tags: deploy
# - deploy
# - swarm_init

- name: Manager services
  hosts: managers
  roles:
    - role: pre_config
      tags: preconfig
# - swarm_join

- name: Worker services
  hosts: workers
  roles:
    - role: pre_config
      tags: preconfig
    # - swarm_join
