---
- name: Конфигурирование секрета {{ name_item }}
  block:
    - name: "[{{ name_item }}] создание секрета"
      include_tasks: secret-create.yml

  rescue:
    - name: "[{{ name_item }}] удаление секрета"
      community.docker.docker_swarm_service:
        name: "{{ name_item }}"
        state: absent

    - name: "[{{ name_item }}] создание секрета"
      include_tasks: secret-create.yml
