---
- name: "[{{ name_item }}] создание секрета"
  vars:
    envFile: "{{ lookup('file', '{{ name_item }}/.env') }}"
  community.docker.docker_secret:
    name: "{{ name_item }}.env"
    data: "{{ envFile | b64encode }}"
    labels:
      secret: "{{ envFile | hash('sha1') }}"
    data_is_b64: true
    state: present
