---
- name: Установка Docker
  become: true
  block:
    - name: Добавляем Universe
      ansible.builtin.apt_repository:
        repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
        state: present
    - name: Установка дополнительных пакетов
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        update-cache: true
        cache_valid_time: 86400
    - name: Создание директории для хранения ключа Docker
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"
    - name: Добавление ключа Docker
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0755"
    - name: Установка стабильного репозитория
      ansible.builtin.apt_repository:
        repo: >
          deb
          [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc]
          https://download.docker.com/linux/ubuntu
          {{ ansible_distribution_release }}
          stable
    - name: Установка дополнительных пакетов
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        update-cache: true
    - name: Проверка что Docker установлен
      ansible.builtin.service:
        name: docker
        state: restarted
        enabled: true
- name: Завершение установки
  become: true
  block:
    - name: Добавление пользователя в группу Docker
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        group: docker
        append: true
    - name: Перезагрузка системв
      ansible.builtin.reboot:
